### ISSUE TITLE
并未在控制面板里找到《控制面板支持 meta 修改版本和官方版本切换和更新》 功能[Feature] 

### ISSUE THREAD

**Issue by AlasJiahui** [vernesong/OpenClash#2598]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

并未在控制面板里找到《控制面板支持 meta 修改版本和官方版本切换和更新》 功能，包括全局设置-meta设置

### Describe the Solution

能否将《控制面板支持 meta 修改版本和官方版本切换和更新》功能转移到meta设置里

**Comment by iadao** [comment]
全局设置-外部控制

**Comment by AlasJiahui** [comment]
> 全局设置-外部控制
谢谢，原来是这么个意思
