### ISSUE TITLE
[Feature] clash meta 内核更新到 1.6.0

### ISSUE THREAD

**Issue by someway22** [vernesong/OpenClash#3574]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

希望更新 mipsle-softfloat 的 clash meta 内核到 1.6.0

### Describe the Solution

Newifi D2 上的 openclash 0.45.141, 最近几周还是更新不到 1.6.0 的内核。从 clash meta 下载的 clash.meta-linux-mipsle-softfloat-v1.16.0.tgz 解压缩后有 30 多M ，跟 openclash 下载的尺寸对不上啊。过去更新都很快的，不知道现在是什么问题？

**Comment by TGSAN** [comment]
大小对不上应该是upx之类的压缩过

**Comment by someway22** [comment]
> 大小对不上应该是upx之类的压缩过

这样，那应该怎么升级到 1.6.0?

**Comment by skill7899** [comment]
> > 大小对不上应该是upx之类的压缩过
> 
> 这样，那应该怎么升级到 1.6.0?

手动下载，手动升级。

**Comment by caliban511** [comment]
已经无了，，，😂😂😂
