### ISSUE TITLE
[Bug]  Openwrt 23.5 / Openclash无法启动，提示 Meta Running   |   Daemons:   Not Running

### ISSUE THREAD

**Issue by patsnap-guyong** [vernesong/OpenClash#3803]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [ ] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Docker

### OpenWrt Version

OpenWrt 23.05-SNAPSHOT r23791-02272df01c / LuCI openwrt-23.05 branch git-24.072.73299-397b1b2

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

[Bug] Deamons 无法启动， 
Meta   Running

### To Reproduce

第一次安装openclash后，即如此

### OpenClash Log

```log
2024-03-14 03:08:14 Tip: Firewall4 was Detected, Use NFTABLE Rules...
2024-03-14 03:08:14 Tip: DNS Hijacking Mode is Dnsmasq Redirect...
2024-03-14 03:08:14 Step 7: Set Firewall Rules...
2024-03-14 03:08:14 Step 6: Wait For The File Downloading...
2024-03-14 03:08:11 Step 5: Check The Core Status...
2024-03-14 03:08:10 configuration file【/etc/openclash/ENET.yaml】test is successful
2024-03-14 03:08:08 Test The Config File First...
2024-03-14 03:08:08 Tip: Detected The Exclusive Function of The Meta Core, Use Meta Core to Start...
2024-03-14 03:08:08 Step 4: Start Running The Clash Core...
2024-03-14 03:08:08 Tip: Start Running Custom Overwrite Scripts...
2024-03-14 03:08:07 Tip: You have seted the authentication of SOCKS5/HTTP(S) proxy with【Clash:2wSzkBNJ】
2024-03-14 03:08:06 Step 3: Modify The Config File...
2024-03-14 03:08:06 CN Domains List Update Successful!
2024-03-14 03:08:06 CN Domains List Has Been Updated, Starting To Replace The Old Version...
2024-03-14 03:08:05 CN Domains List Download Success, Check Updated...
2024-03-14 03:08:04 Start Downloading The CN Domains List...
2024-03-14 03:08:04 Chnroute6 Cidr List Update Successful!
2024-03-14 03:08:04 Chnroute6 Cidr List Has Been Updated, Starting To Replace The Old Version...
2024-03-14 03:08:04 Chnroute6 Cidr List Download Success, Check Updated...
2024-03-14 03:08:03 Start Downloading The Chnroute6 Cidr List...
2024-03-14 03:08:03 Chnroute Cidr List Update Successful!
2024-03-14 03:08:03 Chnroute Cidr List Has Been Updated, Starting To Replace The Old Version...
2024-03-14 03:08:03 Chnroute Cidr List Download Success, Check Updated...
2024-03-14 03:08:03 Start Downloading The Chnroute Cidr List...
2024-03-14 03:08:03 Tip: Detected that the Chnroute Cidr List Format is wrong, Ready to Reformat...
2024-03-14 03:08:02 Step 2: Check The Components...
2024-03-14 03:08:02 Step 1: Get The Configuration...
2024-03-14 03:08:02 OpenClash Start Running...
2024-03-14 03:08:02 Step 6: Delete OpenClash Residue File...
2024-03-14 03:08:01 Step 5: Restart Dnsmasq...
2024-03-14 03:08:01 Step 4: Close The Clash Core Process...
2024-03-14 03:08:01 Step 3: Close The OpenClash Daemons...
2024-03-14 03:08:01 Step 2: Delete OpenClash Firewall Rules...
2024-03-14 03:08:01 Step 1: Backup The Current Groups State...
2024-03-14 03:08:01 OpenClash Stoping...
2024-03-14 03:08:01 OpenClash Restart...
2024-03-14 03:08:01 Config File【ENET】Update Successful!
2024-03-14 03:08:01 Config File【ENET】Download Successful, Start To Create...
2024-03-14 03:08:01 Config File Test Successful, Check If There is Any Update...
2024-03-14 03:08:00 Start Updating Config File【ENET】...
2024-03-14 03:07:59 【/etc/openclash/config/ENET.yaml】Config File Does Not Exist, You Have Set Subscription Information, Ready To Download...
2024-03-14 03:07:59 OpenClash Start Running...
2024-03-14 03:07:59 Step 6: Delete OpenClash Residue File...
2024-03-14 03:07:58 Step 5: Restart Dnsmasq...
2024-03-14 03:07:58 Step 4: Close The Clash Core Process...
2024-03-14 03:07:58 Step 3: Close The OpenClash Daemons...
2024-03-14 03:07:58 Step 2: Delete OpenClash Firewall Rules...
2024-03-14 03:07:57 Step 1: Backup The Current Groups State...
2024-03-14 03:07:57 OpenClash Stoping...
2024-03-14 03:07:57 OpenClash Restart...
2024-03-14 03:06:25 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...
```

### Expected Behavior

openclash可以正常启动

### Additional Context

![image](https://github.com/vernesong/OpenClash/assets/121414356/c3f3a17d-b8d6-4402-9284-d3c863e53c16)

**Comment by patsnap-guyong** [comment]
问题同 https://github.com/vernesong/OpenClash/issues/3682
