### ISSUE TITLE
[Bug] v0.46.005-beta Meta + FakeIP + 劫持 Dnsmasq +绕过中国大陆功能工作不正常

### ISSUE THREAD

**Issue by Aethersailor** [vernesong/OpenClash#3836]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.005-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05

### Bug on Platform

Linux-arm64

### Describe the Bug

v0.46.005-beta版本，在启用 Meta + FakeIP混合 + Dnsmasq 劫持的情况下
若勾选绕过中国大陆，则会导致所有的国内域名会被解析成 FakeIP 并且无法访问，且日志提示劫持 53 至 OpenClash 内核后等待十几分钟也没有提示劫持还原
若不勾选绕过大陆，则会导致国内域名全部无法解析，Dnsmasq工作不正常

nslookup www.baidu.com 返回如下内容
[root@OpenWrt:11:17 PM ~] # nslookup www.baidu.com 127.0.0.1:53
nslookup: write to '127.0.0.1:53': Connection refused
;; connection timed out; no servers could be reached

PS，我手头有三台设备，三台设备的 OpenClash 均使用的相同版本和设置，其中这一台不能工作的设备用的是 Firewall，而另外两台用的 Firewall4 的设备则一切正常

### To Reproduce

使用 Meta最新dev版本 + FakeIP混合 + Dnsmasq 劫持 + 绕过中国大陆

### OpenClash Log

```log
我想生成日志，但是一直卡在
收集数据...

Loading 等待命令执行完成...
一直卡在这一步，所以暂时无法提供日志了

但是系统日志内会反复出现如下内容：
Mon Apr  8 22:21:42 2024 daemon.crit dnsmasq[8003]: recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/dnsmasq.d/dnsmasq_openclash_chnroute_pass.conf
Mon Apr  8 22:21:42 2024 daemon.crit dnsmasq[8003]: FAILED to start up
Mon Apr  8 22:21:47 2024 daemon.crit dnsmasq[8089]: recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/dnsmasq.d/dnsmasq_openclash_chnroute_pass.conf
Mon Apr  8 22:21:47 2024 daemon.crit dnsmasq[8089]: FAILED to start up
Mon Apr  8 22:21:53 2024 daemon.crit dnsmasq[8130]: recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/dnsmasq.d/dnsmasq_openclash_chnroute_pass.conf
Mon Apr  8 22:21:53 2024 daemon.crit dnsmasq[8130]: FAILED to start up
Mon Apr  8 22:21:58 2024 daemon.crit dnsmasq[8178]: recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/dnsmasq.d/dnsmasq_openclash_chnroute_pass.conf
Mon Apr  8 22:21:58 2024 daemon.crit dnsmasq[8178]: FAILED to start up
Mon Apr  8 22:22:03 2024 daemon.crit dnsmasq[8219]: recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/dnsmasq.d/dnsmasq_openclash_chnroute_pass.conf
Mon Apr  8 22:22:03 2024 daemon.crit dnsmasq[8219]: FAILED to start up
Mon Apr  8 22:22:09 2024 daemon.crit dnsmasq[8260]: recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/dnsmasq.d/dnsmasq_openclash_chnroute_pass.conf
Mon Apr  8 22:22:09 2024 daemon.crit dnsmasq[8260]: FAILED to start up

打开以上报错信息涉及的文件，只有一行内容
ipset=/services.googleapis.cn/china_ip_route_pass
```

### Expected Behavior

希望能正常工作
