### ISSUE TITLE
[Feature] V大，`meta` 内核已支持 `HTTPUpgrade`，能否添加？！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#3838]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

https://github.com/MetaCubeX/mihomo/commit/3e0bd65135dbd8e1287adc9f04ed1e9472939dd1
